---
- hosts: common
  become: yes
  remote_user: adminfpi
  gather_facts: no
  tasks:

  #### SECURITY COMPLIANCE ###########################################

    - name: Passwordless Sudo For sudo Group
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add User to sudo Group
      user:
        name=adminfpi
        groups=sudo
        append=yes
        state=present
        createhome=yes